version: '3'

services:
  mongodb:
    image: mongo
    container_name: "mongodb"
    environment:
        - MONGO_DATA_DIR=/data/db
        - MONGO_LOG_DIR=/dev/null
        - MONGODB_USER="admin" 
        - MONGODB_PASS="admin"
    volumes:
        - ./data/db:/data/db
    ports:
        - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet
    #command: mongod --auth --smallfiles --logpath=/dev/null # using auth